export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';

export const CREATE_ENEMY = 'CREATE_ENEMY';
export const MOVE_PLAYER = 'MOVE_PLAYER';
export const ADD_ENEMY_COUNT = 'ADD_ENEMY_COUNT';
export const MOVE_ENEMY = 'MOVE_ENEMY';
export const CHANGE_ENEMY_DIRECTION = 'CHANGE_ENEMY_DIRECTION';
export const CHANGE_PLAYER_DIRECTION = 'CHANGE_PLAYER_DIRECTION';
export const PLAYER_HIT_WALL = 'PLAYER_HIT_WALL';
export const PLAYER_HAS_SCORED = 'PLAYER_HAS_SCORED';
export const BULLET_INITIATE = 'BULLET_INITIATE';
export const BULLET_IS_MOVING = 'BULLET_IS_MOVING';
export const BULLET_HAS_STOPPED = 'BULLET_HAS_STOPPED';
export const ENEMY_HIT_PLAYER = 'ENEMY_HIT_PLAYER';
export const SHOW_GAME_OVER = 'SHOW_GAME_OVER';
export const TOP_SCORES = 'TOP_SCORES';


/* ======== MENU ========== */
export const LINK_CLICKED = 'LINK_CLICKED';
export const ACTIVATE_MENU = 'ACTIVATE_MENU';
